version: '2'
services:
    jhipsteradmin-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhipsterAdmin/mongodb/:/data/db/
